export const BUDGET_LABELS = {
  'CDL_BDG_PAGE_TITLE': "Budget Category",
  'CDL_BDG_PAGE_SUBTITLE': "Manage budget categories step by step.",
  'CDL_BDG_LIST_NEW_BUTTON': "New Budget Category",
  'CDL_BDG_LIST_EMPTY_STATE': "No budget categories yet. Add one to get started.",
  'CDL_BDG_LIST_TABLE_CHARGE_TYPE': "Charge Type",
  'CDL_BDG_LIST_TABLE_GROUP_NAME': "Group Name",
  'CDL_BDG_LIST_TABLE_CATEGORY_NAME': "Category Name",
  'CDL_BDG_LIST_TABLE_SERVICE_NAME': "Service Name",
  'CDL_BDG_LIST_TABLE_PROVISIONAL_CODE': "Provisional Code",
  'CDL_BDG_LIST_TABLE_ACTIONS': "Actions",
  'CDL_BDG_FORM_CHARGE_TYPE': "Charge Type",
  'CDL_BDG_FORM_GROUP_NAME': "Group Name",
  'CDL_BDG_FORM_CATEGORY_CODE': "Category Code",
  'CDL_BDG_FORM_CATEGORY_NAME': "Category Name",
  'CDL_BDG_FORM_CATEGORY_SUB_CODE': "Category Sub Code",
  'CDL_BDG_FORM_CATEGORY_SUB_NAME': "Category Sub Name",
  'CDL_BDG_FORM_CATEGORY_SUB_TO_SUB_CODE': "Category Sub-to-Sub Code",
  'CDL_BDG_FORM_CATEGORY_SUB_TO_SUB_NAME': "Category Sub-to-Sub Name",
  'CDL_BDG_FORM_SERVICE_CODE': "Service Code",
  'CDL_BDG_FORM_SERVICE_NAME': "Service Name",
  'CDL_BDG_FORM_PROVISIONAL_BUDGET_CODE': "Provisional Budget Code",
  'CDL_BDG_FORM_CHARGE_TYPE_ID': "Charge Type ID",
  'CDL_BDG_SECTION_GENERAL': "General",
  'CDL_BDG_SECTION_CATEGORIZATION': "Categorization",
  'CDL_BDG_SECTION_PROVISIONAL': "Provisional Budget",
  'CDL_BDG_STEP_DETAILS': "Details",
  'CDL_BDG_STEP_DOCUMENTS': "Documents",
  'CDL_BDG_STEP_REVIEW': "Review",
  'CDL_BDG_DOC_TITLE' : "Documents",
  'CDL_BDG_MASTER_BUDGET': "Master Budget",
  'CDL_BDG_DOC_DESCRIPTION' : "Upload budget category documents (optional).",
  'CDL_BDG_DOC_SAVE_HEADING': "Save details first",
  'CDL_BDG_DOC_SAVE_MESSAGE':
    "Please save the budget category details before uploading documents.",

  // Common UI labels
  'CDL_COMMON_ACTION': "Action",
  'CDL_COMMON_RETRY': "Retry",
  'CDL_COMMON_CANCEL': "Cancel",
  'CDL_COMMON_ADD': "Add",
  'CDL_COMMON_UPDATE': "Update",
  'CDL_COMMON_ADDING': "Adding...",
  'CDL_COMMON_UPDATING': "Updating...",
  'CDL_COMMON_LOADING': "Loading...",
  'CDL_COMMON_VALIDATE_ACCOUNT': "Validate Account",
  'CDL_COMMON_VALIDATE_BIC': "Validate BIC",
  'CDL_COMMON_REQUIRED_FIELDS_PREFIX': "Please fill in the required fields:",
  'CDL_COMMON_DROPDOWNS_LOAD_FAILED': "Failed to load dropdown options. Please refresh the page.",
  'CDL_COMMON_SUBMIT_WAIT': "Please wait for dropdown options to load before submitting.",
};

export const MASTER_BUDGET_LABELS = {
  'PAGE_TITLE': "CDL_BDG_PAGE_TITLE",
  'PAGE_SUBTITLE': "CDL_BDG_PAGE_SUBTITLE",
  LIST: {
    'NEW_BUTTON': "CDL_BDG_LIST_NEW_BUTTON",
    'EMPTY_STATE': "CDL_BDG_LIST_EMPTY_STATE",
    TABLE_HEADERS: {
      'CHARGE_TYPE': "CDL_BDG_LIST_TABLE_CHARGE_TYPE",
      'GROUP_NAME': "CDL_BDG_LIST_TABLE_GROUP_NAME",
      'CATEGORY_NAME': "CDL_BDG_LIST_TABLE_CATEGORY_NAME",
      'SERVICE_NAME': "CDL_BDG_LIST_TABLE_SERVICE_NAME",
      'PROVISIONAL_CODE': "CDL_BDG_LIST_TABLE_PROVISIONAL_CODE",
      'ACTIONS': "CDL_BDG_LIST_TABLE_ACTIONS",
    },
  },
  FORM_FIELDS: {
    'CHARGE_TYPE': "CDL_BDG_FORM_CHARGE_TYPE",
    'CHARGE_TYPE_ID': "CDL_BDG_FORM_CHARGE_TYPE_ID",
    'GROUP_NAME': "CDL_BDG_FORM_GROUP_NAME",
    'CATEGORY_CODE': "CDL_BDG_FORM_CATEGORY_CODE",
    'CATEGORY_NAME': "CDL_BDG_FORM_CATEGORY_NAME",
    'CATEGORY_SUB_CODE': "CDL_BDG_FORM_CATEGORY_SUB_CODE",
    'CATEGORY_SUB_NAME': "CDL_BDG_FORM_CATEGORY_SUB_NAME",
    'CATEGORY_SUB_TO_SUB_CODE': "CDL_BDG_FORM_CATEGORY_SUB_TO_SUB_CODE",
    'CATEGORY_SUB_TO_SUB_NAME': "CDL_BDG_FORM_CATEGORY_SUB_TO_SUB_NAME",
    'SERVICE_CODE': "CDL_BDG_FORM_SERVICE_CODE",
    'SERVICE_NAME': "CDL_BDG_FORM_SERVICE_NAME",
    'PROVISIONAL_BUDGET_CODE': "CDL_BDG_FORM_PROVISIONAL_BUDGET_CODE",
  },
  SECTION_TITLES: {
    'GENERAL': "CDL_BDG_SECTION_GENERAL",
    'CATEGORIZATION': "CDL_BDG_SECTION_CATEGORIZATION",
    'PROVISIONAL': "CDL_BDG_SECTION_PROVISIONAL",
  },
  STEPS: {
    'DETAILS': "CDL_BDG_STEP_DETAILS",
    'DOCUMENTS': "CDL_BDG_STEP_DOCUMENTS",
    'REVIEW': "CDL_BDG_STEP_REVIEW",
  },
  DOCUMENTS: {
    'TITLE': "CDL_BDG_DOC_TITLE",
    'DESCRIPTION': "CDL_BDG_DOC_DESCRIPTION",
    'SAVE_HEADING': "CDL_BDG_DOC_SAVE_HEADING",
    'SAVE_MESSAGE': "CDL_BDG_DOC_SAVE_MESSAGE",
  },
  FALLBACKS: {
    'PAGE_TITLE': "Budget Category",
    'PAGE_SUBTITLE': "Manage budget categories step by step.",
    LIST: {
      'NEW_BUTTON': "New Budget Category",
      'EMPTY_STATE': "No budget categories yet. Add one to get started.",
      TABLE_HEADERS: {
        'CHARGE_TYPE': "Charge Type",
        'GROUP_NAME': "Group Name",
        'CATEGORY_NAME': "Category Name",
        'SERVICE_NAME': "Service Name",
        'PROVISIONAL_CODE': "Provisional Code",
        'ACTIONS': "Actions",
      },
    },
    FORM_FIELDS: {
      'CHARGE_TYPE': "Charge Type",
      'CHARGE_TYPE_ID': "Charge Type ID",
      'GROUP_NAME': "Group Name",
      'CATEGORY_CODE': "Category Code",
      'CATEGORY_NAME': "Category Name",
      'CATEGORY_SUB_CODE': "Category Sub Code",
      'CATEGORY_SUB_NAME': "Category Sub Name",
      'CATEGORY_SUB_TO_SUB_CODE': "Category Sub-to-Sub Code",
      'CATEGORY_SUB_TO_SUB_NAME': "Category Sub-to-Sub Name",
      'SERVICE_CODE': "Service Code",
      'SERVICE_NAME': "Service Name",
      'PROVISIONAL_BUDGET_CODE': "Provisional Budget Code",
    },
    SECTION_TITLES: {
      'GENERAL': "General",
      'CATEGORIZATION': "Categorization",
      'PROVISIONAL': "Provisional Budget",
    },
    STEPS: {
      'DETAILS': "Details",
      'DOCUMENTS': "Documents",
      'REVIEW': "Review",
    },
    DOCUMENTS: {
      'TITLE': "Documents",
      'DESCRIPTION': "Upload budget category documents (optional).",
      'SAVE_HEADING': "Save details first",
      'SAVE_MESSAGE':
        "Please save the budget category details before uploading documents.",
    },
  },
};

export function getBudgetLabel(configId: string): string {
  return BUDGET_LABELS[configId as keyof typeof BUDGET_LABELS] ?? configId;
}

export default BUDGET_LABELS;
