// // Build Partner Asset label mapping from BUILD_PARTNER_ASSET API response
// // Maps configId to configValue for easy lookup and usage in components

// export const BUILD_PARTNER_ASSET_LABELS = {
//   // Main Management Firm Details
//   CDL_MF_DETAILS: 'Management Firm Details',
//   CDL_MF_REFID: '',
//   CDL_MF_REGNO: 'RERA Registration Number',
//   CDL_MF_NAME: 'Asset Name',
//   CDL_MF_CLASSIFICATION: 'Asset Classification',
//   CDL_MF_LOCATION: 'Asset Location',
//   CDL_MF_CIF: 'Customer Information File (CIF) Number',
//   CDL_MF_STATUS: 'Asset Status',
//   CDL_MF_ACC_STATUS: 'Asset Account Status',
//   CDL_MF_ACC_STATUS_DATE: 'Asset Account Status Date',
//   CDL_MF_REG_DATE: 'Asset Registration Date',
//   CDL_MF_EST_DATE: 'Estimated Commencement Date',
//   CDL_MF_EST_COMPLETION_DATE: 'Estimated Completion Date',
//   CDL_MF_PRIMARY_RETENTION: 'Primary Retention(%)',
//   CDL_MF_SECONDARY_RETENTION: 'Supplementary Retention(%)',
//   CDL_MF_AGG_RETENTION: 'Aggregate Retention(%)',
//   CDL_MF_RETENTION_START_DATE: 'Retention Start Date',
//   CDL_MF_MGMT_EXPENSES: 'Asset Management Expenses(%)',
//   CDL_MF_MARKETING_COST: 'Marketing Costs(%)',
//   CDL_MF_BROK_FEES: 'Brokerage Fees',
//   CDL_MF_ADVTG_COST: 'Advertising Costs',
//   CDL_MF_LANDOWNER_NAME: 'Landowner Name',
//   CDL_MF_ASST_COMP_PER: 'Asset Completion Percentage',
//   CDL_MF_TRAN_CUR: 'Transaction Currency',
//   CDL_MF_ACT_COST: 'Actual Build Cost',
//   CDL_MF_TOTAL_UNIT: 'Total Units',
//   CDL_MF_ADD_NOTES: 'Additional Notes',


//   // CDL_MF_DETAILS: 'Management Firms Asset Details',
//   // CDL_MF_REFID: '',
//   // CDL_MF_REGNO: 'HOA Regisntartion Number',
//   // CDL_MF_NAME: 'Asset Name',
//   // CDL_MF_CLASSIFICATION: 'Asset Classification',
//   // CDL_MF_LOCATION: 'Asset Location',
//   // CDL_MF_CIF: 'Customer Information File (CIF) Number',
//   // CDL_MF_STATUS: 'Asset Status',
//   // CDL_MF_ACC_STATUS: 'Asset Account Status',
//   // CDL_MF_ACC_STATUS_DATE: 'Asset Account Status Date',
//   // CDL_MF_REG_DATE: 'Asset Registration Date',
//   // CDL_MF_EST_DATE: 'Estimated Commencement Date',
//   // CDL_MF_EST_COMPLETION_DATE: 'Estimated Completion Date',
//   // CDL_MF_PRIMARY_RETENTION: 'Primary Retention(%)',
//   // CDL_MF_SECONDARY_RETENTION: 'Supplementary Retention(%)',
//   // CDL_MF_AGG_RETENTION: 'Aggregate Retention(%)',
//   // CDL_MF_RETENTION_START_DATE: 'Retention Start Date',
//   // CDL_MF_MGMT_EXPENSES: 'Asset Management Expenses(%)',
//   // CDL_MF_MARKETING_COST: 'Marketing Costs(%)',
//   // CDL_MF_BROK_FEES: 'Brokerage Fees',
//   // CDL_MF_ADVTG_COST: 'Advertising Costs',
//   // CDL_MF_LANDOWNER_NAMEOST: 'Landowner Name',
//   // CDL_MF_ASST_COMP_PER: 'Asset Completion Percentage',
//   // CDL_MF_TRAN_CUR: 'Transaction Currency',
//   // CDL_MF_ACT_COST: 'Actual Build Cost',
//   // CDL_MF_TOTAL_UNIT: 'Total Units',
//   // CDL_MF_ADD_NOTES: 'Additional Notes',

//   // Build Partner Information
//   // CDL_MF_AR_ID: 'Developer Id',
//   // CDL_MF_AR_CIF: 'Developer CIF',
//   // CDL_MF_AR_NAME: 'Developer Name',
//   // CDL_MF_AR_STATUS: 'Project Status',
//   // CDL_MF_AR_APPROVAL_STATUS: 'Approval Status',
//   CDL_MF_AR_ID: 'Asset Registry ID',
//   CDL_MF_AR_CIF: 'Asset Registry CIF',
//   CDL_MF_AR_NAME: 'Master Asset Registry Name',
//   CDL_MF_AR_STATUS: 'Status',
//   CDL_MF_AR_APPROVAL_STATUS: 'Approval Status',

//   // Special Regulatory and Management
//   CDL_MF_SP_REG_APPROVAL: 'Special Regulatory Approval 09876',
//   CDL_MF_RES_PAYMENT_TYPE: 'Restricted Payment Type222',
//   CDL_MF_ASS_MANAGER: 'Asset Manager',
//   CDL_MF_BACKUP_MANAGER: 'Backup Manager',
//   CDL_MF_RM: 'Relationship Manager',
//   CDL_MF_ARM: 'Assistant RM',
//   CDL_MF_TL: 'Team Lead Name09876',
//   CDL_MF_DOC_VALIDITY: 'Document Validity Date',

//   // Account Details
//   CDL_MF_ACC_NO: 'Trust Account Number111',
//   CDL_MF_ACC_IBAN: 'IBAN111',
//   CDL_MF_ACC_OPENDATE: 'Account Opening Date111',
//   CDL_MF_ACC_NAME: 'Account Name111',
//   CDL_MF_ACC_CUR: 'Account Currency111',
//   CDL_MF_ACC_RETENTION: 'Retention Account',
//   CDL_MF_ACC_SUBCONS: 'Sub-Construction Account',
//   CDL_MF_ACC_CORP: 'Corporate Account',
//   CDL_MF_ACC_VALIDATION: 'Account Validation',

//   // Beneficiary Details
//   CDL_MF_BENE_INFO: 'Beneficiary Banking Details',
//   CDL_MF_BENE_EXP: 'Expense Category',
//   CDL_MF_BENE_TRANSFER: 'Transfer Method',
//   CDL_MF_BENE_REFID: 'Beneficiary Reference ID',
//   CDL_MF_BENE_NAME: 'Beneficiary Full Name',
//   CDL_MF_BENE_BANK: 'Bank Name',
//   CDL_MF_BENE_ACC: 'Bank Account Number',
//   CDL_MF_BENE_IBAN: 'Beneficiary IBAN',
//   CDL_MF_BENE_BIC: 'Beneficiary Swift',
//   CDL_MF_BENE_ROUTING: 'Beneficiary Routing Code',
//   CDL_MF_BENE_SWIFT: 'Validate Swift',
//   CDL_MF_ACC_VAL: 'Validate Account',
//   CDL_MF_BENE_DOC_TEMPLATE: 'Download Template',
//   CDL_MF_BENE_UPLOAD_BENE: 'Upload Beneficiary Details',

//   // Payment Plan
//   CDL_MF_PAYMENT_PLAN: 'Payment Plan',
//   CDL_MF_ADD_INSTALLMENT: 'Add Installment',
//   CDL_MF_INSTALLMENT_NO: 'Installment Number',
//   CDL_MF_INSTALLMENT_PER: 'Installment Percentage',
//   CDL_MF_PROJ_COM_PER: 'Project Completion Percentage',

//   // Project Financial
//   CDL_MF_FINANCIAL: 'Project Financial',
//   CDL_MF_EST_ASS_COST: 'Project Estimate Cost',
//   CDL_MF_TOTAL_REVENUE: 'Revenue',
//   CDL_MF_BUILD_COST: 'Construction Cost',
//   CDL_MF_ASST_MGMT_EXP: 'Project Management Expense',
//   CDL_MF_LAND_ACQ_COST: 'Land Cost',
//   CDL_MF_MARK_EXP: 'Marketing Expense',
//   CDL_MF_TRAN_DATE: 'Date',
//   CDL_MF_ACTUAL_ASSEST_COST: 'Project Actual Cost',
//   CDL_MF_TOTAL_UNIT_SOLD: 'Sold Value',
//   CDL_MF_INFRA_COST: 'Infrastructure Cost',
//   CDL_MF_CASH_FROM_UNIT: 'Cash Received from the Unit Holder',
//   CDL_MF_FUND_OUT_ESCROW: 'Out Of Escrow',
//   CDL_MF_FUND_WITHIN_ESCROW: 'Within Escrow',
//   CDL_MF_TOTAL_AMOUNT: 'Total',
//   CDL_MF_EXCEP_CAP_VAL: 'Exceptional Cap Value',
//   CDL_MF_MORTGAGE_AMT: 'Mortgage',
//   CDL_MF_VAT_AMT: 'Vat Payment',
//   CDL_MF_OQOOD_FEES: 'Ogood',
//   CDL_MF_REFUND_AMT: 'Refund',
//   CDL_MF_RETEN_ACC_BAL: 'Balance in Retention A/C',
//   CDL_MF_TRUST_ACC_BAL: 'Balance in Trust A/C',
//   CDL_MF_SUBCONS_ACC_BAL: 'Balance in Subconstruction A/C',
//   CDL_MF_TECH_FEES: 'Techincal Fees',
//   CDL_MF_UNALLO_COST: 'Unidentified Cost',
//   CDL_MF_LOAN: 'Loans/Installments',
//   CDL_MF_OTHER_EXP: 'Others',
//   CDL_MF_TRANS_AMT: 'Transferred',
//   CDL_MF_FORFEIT_AMT: 'Forfeited',
//   CDL_MF_DEV_EQUITY_CONT: 'Developers Equity',
//   CDL_MF_AMANAT_FUND: 'Amanat Fund',
//   CDL_MF_OTHER_WITHDRAW: 'Others Withdrawal',
//   CDL_MF_OQOOD_OTHER_PMT: 'Ogood/Others fees and Payments',
//   CDL_MF_VAT_DEPOSIT_AMT: 'Vat Deposit',
//   CDL_MF_PROFIT_ERND: 'Credit Interest/ Profit earned for retention A',
//   CDL_MF_REIMB_AMT: 'Re-imbursement',
//   CDL_MF_PMT_FRM_RETENTION: 'Payment From Retention A/C',
//   CDL_MF_CAP_VAT_AMT: 'VAT Capped',
//   CDL_MF_INT_ERND_ESCROW: 'Credit Interest/ Profit earned for escrow A/C',
//   CDL_MF_CLOSURE: 'Project Closure',
//   CDL_MF_TOTAL_AMT_RECEIVED: 'Total Income Fund',
//   CDL_MF_TOTAL_DIS_PMT: 'Total Payment',
//   CDL_MF_DOC_ACTION: 'Available Actions',
// }

// // Utility function to get label by configId
// export const getBuildPartnerAssetLabel = (configId) => {
//   return BUILD_PARTNER_ASSET_LABELS[configId] || configId
// }

// // Utility function to get all labels for a specific category
// export const getBuildPartnerAssetLabelsByCategory = (category) => {
//   const categories = {
//     details: [
//       'CDL_MF_DETAILS',
//       'CDL_MF_REFID',
//       'CDL_MF_REGNO',
//       'CDL_MF_NAME',
//       'CDL_MF_CLASSIFICATION',
//       'CDL_MF_LOCATION',
//       'CDL_MF_CIF',
//       'CDL_MF_STATUS',
//       'CDL_MF_ACC_STATUS',
//       'CDL_MF_ACC_STATUS_DATE',
//       'CDL_MF_REG_DATE',
//       'CDL_MF_EST_DATE',
//       'CDL_MF_EST_COMPLETION_DATE',
//     ],
//     retention: [
//       'CDL_MF_PRIMARY_RETENTION',
//       'CDL_MF_SECONDARY_RETENTION',
//       'CDL_MF_AGG_RETENTION',
//       'CDL_MF_RETENTION_START_DATE',
//     ],
//     expenses: [
//       'CDL_MF_MGMT_EXPENSES',
//       'CDL_MF_MARKETING_COST',
//       'CDL_MF_BROK_FEES',
//       'CDL_MF_ADVTG_COST',
//     ],
//     management: [
//       'CDL_MF_SP_REG_APPROVAL',
//       'CDL_MF_RES_PAYMENT_TYPE',
//       'CDL_MF_ASS_MANAGER',
//       'CDL_MF_BACKUP_MANAGER',
//       'CDL_MF_RM',
//       'CDL_MF_ARM',
//       'CDL_MF_TL',
//       'CDL_MF_DOC_VALIDITY',
//       'CDL_MF_DOC_ACTION',
//     ],
//     account: [
//       'CDL_MF_ACC_NO',
//       'CDL_MF_ACC_IBAN',
//       'CDL_MF_ACC_OPENDATE',
//       'CDL_MF_ACC_NAME',
//       'CDL_MF_ACC_CUR',
//       'CDL_MF_ACC_RETENTION',
//       'CDL_MF_ACC_SUBCONS',
//       'CDL_MF_ACC_CORP',
//       'CDL_MF_ACC_VALIDATION',
//     ],
//     beneficiary: [
//       'CDL_MF_BENE_INFO',
//       'CDL_MF_BENE_EXP',
//       'CDL_MF_BENE_TRANSFER',
//       'CDL_MF_BENE_REFID',
//       'CDL_MF_BENE_NAME',
//       'CDL_MF_BENE_BANK',
//       'CDL_MF_BENE_ACC',
//       'CDL_MF_BENE_IBAN',
//       'CDL_MF_BENE_BIC',
//       'CDL_MF_BENE_ROUTING',
//       'CDL_MF_BENE_SWIFT',
//       'CDL_MF_ACC_VAL',
//       'CDL_MF_BENE_DOC_TEMPLATE',
//       'CDL_MF_BENE_UPLOAD_BENE',
//     ],
//     payment_plan: [
//       'CDL_MF_PAYMENT_PLAN',
//       'CDL_MF_ADD_INSTALLMENT',
//       'CDL_MF_INSTALLMENT_NO',
//       'CDL_MF_INSTALLMENT_PER',
//       'CDL_MF_PROJ_COM_PER',
//     ],
//     financial: [
//       'CDL_MF_FINANCIAL',
//       'CDL_MF_EST_ASS_COST',
//       'CDL_MF_TOTAL_REVENUE',
//       'CDL_MF_BUILD_COST',
//       'CDL_MF_ASST_MGMT_EXP',
//       'CDL_MF_LAND_ACQ_COST',
//       'CDL_MF_MARK_EXP',
//       'CDL_MF_TRAN_DATE',
//       'CDL_MF_ACTUAL_ASSEST_COST',
//       'CDL_MF_TOTAL_UNIT_SOLD',
//       'CDL_MF_INFRA_COST',
//       'CDL_MF_CASH_FROM_UNIT',
//       'CDL_MF_FUND_OUT_ESCROW',
//       'CDL_MF_FUND_WITHIN_ESCROW',
//       'CDL_MF_TOTAL_AMOUNT',
//     ],
//     costs: [
//       'CDL_MF_EXCEP_CAP_VAL',
//       'CDL_MF_MORTGAGE_AMT',
//       'CDL_MF_VAT_AMT',
//       'CDL_MF_OQOOD_FEES',
//       'CDL_MF_REFUND_AMT',
//       'CDL_MF_TECH_FEES',
//       'CDL_MF_UNALLO_COST',
//       'CDL_MF_LOAN',
//       'CDL_MF_OTHER_EXP',
//     ],
//     balances: [
//       'CDL_MF_RETEN_ACC_BAL',
//       'CDL_MF_TRUST_ACC_BAL',
//       'CDL_MF_SUBCONS_ACC_BAL',
//     ],
//     transactions: [
//       'CDL_MF_TRANS_AMT',
//       'CDL_MF_FORFEIT_AMT',
//       'CDL_MF_DEV_EQUITY_CONT',
//       'CDL_MF_AMANAT_FUND',
//       'CDL_MF_OTHER_WITHDRAW',
//       'CDL_MF_OQOOD_OTHER_PMT',
//       'CDL_MF_VAT_DEPOSIT_AMT',
//       'CDL_MF_PROFIT_ERND',
//       'CDL_MF_REIMB_AMT',
//       'CDL_MF_PMT_FRM_RETENTION',
//       'CDL_MF_CAP_VAT_AMT',
//       'CDL_MF_INT_ERND_ESCROW',
//     ],
//     closure: [
//       'CDL_MF_CLOSURE',
//       'CDL_MF_TOTAL_AMT_RECEIVED',
//       'CDL_MF_TOTAL_DIS_PMT',
//     ],
//   }

//   return (
//     categories[category]?.map((configId) => ({
//       configId,
//       label: BUILD_PARTNER_ASSET_LABELS[configId],
//     })) || []
//   )
// }

// // Export the full mapping object for direct access
// export default BUILD_PARTNER_ASSET_LABELS


// Build Partner Asset label mapping from BUILD_PARTNER_ASSET API response
// Maps configId to configValue for easy lookup and usage in components

export const BUILD_PARTNER_ASSET_LABELS = {
  // Main Build Partner Asset Details
  CDL_MF_DETAILS: 'Management Firm Details',
  CDL_MF_REFID: '',
  CDL_MF_REGNO: 'Management Firm Registration Number',
  CDL_MF_NAME: 'Management Firm Name',
  CDL_MF_CLASSIFICATION: 'Asset Classification',
  CDL_MF_LOCATION: 'Asset Location',
  CDL_MF_CIF: 'Customer Information File (CIF) Number',
  CDL_MF_STATUS: 'Asset Status',
  CDL_MF_ACC_STATUS: 'Asset Account Status',
  CDL_MF_ACC_STATUS_DATE: 'Asset Account Status Date',
  CDL_MF_REG_DATE: 'Asset Registration Date',
  CDL_MF_EST_DATE: 'Estimated Commencement Date',
  CDL_MF_EST_COMPLETION_DATE: 'Estimated Completion Date',
  CDL_MF_PRIMARY_RETENTION: 'Primary Retention(%)',
  CDL_MF_SECONDARY_RETENTION: 'Supplementary Retention(%)',
  CDL_MF_AGG_RETENTION: 'Aggregate Retention(%)',
  CDL_MF_RETENTION_START_DATE: 'Retention Start Date',
  CDL_MF_MGMT_EXPENSES: 'Asset Management Expenses(%)',
  CDL_MF_MARKETING_COST: 'Marketing Costs(%)',
  CDL_MF_BROK_FEES: 'Brokerage Fees',
  CDL_MF_ADVTG_COST: 'Advertising Costs',
  CDL_MF_LANDOWNER_NAMEOST: 'Landowner Name',
  CDL_MF_ASST_COMP_PER: 'Asset Completion Percentage',
  CDL_MF_TRAN_CUR: 'Transaction Currency',
  CDL_MF_ACT_COST: 'Actual Build Cost',
  CDL_MF_TOTAL_UNIT: 'Total Units',
  CDL_MF_ADD_NOTES: 'Additional Notes',

  // Build Partner Information
  CDL_MF_AR_ID: 'Asset Registry ID',
  CDL_MF_AR_CIF: 'Asset Registry CIF',
  CDL_MF_AR_NAME: 'Master Asset Registry Name',
  CDL_MF_AR_STATUS: 'Status',
  CDL_MF_AR_APPROVAL_STATUS: 'Approval Status',

  // Special Regulatory and Management
  CDL_MF_SP_REG_APPROVAL: 'Special Regulatory Approval 09876',
  CDL_MF_RES_PAYMENT_TYPE: 'Restricted Payment Type222',
  CDL_MF_ASS_MANAGER: 'Asset Manager',
  CDL_MF_BACKUP_MANAGER: 'Backup Manager',
  CDL_MF_RM: 'Relationship Manager',
  CDL_MF_ARM: 'Assistant RM',
  CDL_MF_TL: 'Team Lead Name09876',
  CDL_MF_DOC_VALIDITY: 'Document Validity Date',

  // Account Details
  CDL_MF_ACC_NO: 'Trust Account Number111',
  CDL_MF_ACC_IBAN: 'IBAN111',
  CDL_MF_ACC_OPENDATE: 'Account Opening Date111',
  CDL_MF_ACC_NAME: 'Account Name111',
  CDL_MF_ACC_CUR: 'Account Currency111',
  CDL_MF_ACC_RETENTION: 'Retention Account',
  CDL_MF_ACC_SUBCONS: 'Sub-Construction Account',
  CDL_MF_ACC_CORP: 'Corporate Account',
  CDL_MF_ACC_VALIDATION: 'Account Validation',

  // Beneficiary Details
  CDL_MF_BENE_INFO: 'Beneficiary Banking Details',
  CDL_MF_BENE_EXP: 'Expense Category',
  CDL_MF_BENE_TRANSFER: 'Transfer Method',
  CDL_MF_BENE_REFID: 'Beneficiary Reference ID',
  CDL_MF_BENE_NAME: 'Beneficiary Full Name',
  CDL_MF_BENE_BANK: 'Bank Name',
  CDL_MF_BENE_ACC: 'Bank Account Number',
  CDL_MF_BENE_IBAN: 'Beneficiary IBAN',
  CDL_MF_BENE_BIC: 'Beneficiary Swift',
  CDL_MF_BENE_ROUTING: 'Beneficiary Routing Code',
  CDL_MF_BENE_SWIFT: 'Validate Swift',
  CDL_MF_ACC_VAL: 'Validate Account',
  CDL_MF_BENE_DOC_TEMPLATE: 'Download Template',
  CDL_MF_BENE_UPLOAD_BENE: 'Upload Beneficiary Details',

  // Payment Plan
  CDL_MF_PAYMENT_PLAN: 'Payment Plan',
  CDL_MF_ADD_INSTALLMENT: 'Add Installment',
  CDL_MF_INSTALLMENT_NO: 'Installment Number',
  CDL_MF_INSTALLMENT_PER: 'Installment Percentage',
  CDL_MF_PROJ_COM_PER: 'Management Firm Completion Percentage',

  // Project Financial
  CDL_MF_FINANCIAL: 'Management Firm Financial',
  CDL_MF_EST_ASS_COST: 'Management Firm Estimate Cost',
  CDL_MF_TOTAL_REVENUE: 'Revenue',
  CDL_MF_BUILD_COST: 'Construction Cost',
  CDL_MF_ASST_MGMT_EXP: 'Management Firm Management Expense',
  CDL_MF_LAND_ACQ_COST: 'Land Cost',
  CDL_MF_MARK_EXP: 'Marketing Expense',
  CDL_MF_TRAN_DATE: 'Date',
  CDL_MF_ACTUAL_ASSEST_COST: 'Management Firm Actual Cost',
  CDL_MF_TOTAL_UNIT_SOLD: 'Sold Value',
  CDL_MF_INFRA_COST: 'Infrastructure Cost',
  CDL_MF_CASH_FROM_UNIT: 'Cash Received from the Unit Holder',
  CDL_MF_FUND_OUT_ESCROW: 'Out Of Escrow',
  CDL_MF_FUND_WITHIN_ESCROW: 'Within Escrow',
  CDL_MF_TOTAL_AMOUNT: 'Total',
  CDL_MF_EXCEP_CAP_VAL: 'Exceptional Cap Value',
  CDL_MF_MORTGAGE_AMT: 'Mortgage',
  CDL_MF_VAT_AMT: 'Vat Payment',
  CDL_MF_OQOOD_FEES: 'Ogood',
  CDL_MF_REFUND_AMT: 'Refund',
  CDL_MF_RETEN_ACC_BAL: 'Balance in Retention A/C',
  CDL_MF_TRUST_ACC_BAL: 'Balance in Trust A/C',
  CDL_MF_SUBCONS_ACC_BAL: 'Balance in Subconstruction A/C',
  CDL_MF_TECH_FEES: 'Techincal Fees',
  CDL_MF_MF_NAME: 'Master Management Firm Name',
  CDL_MF_UNALLO_COST: 'Unidentified Cost',
  CDL_MF_LOAN: 'Loans/Installments',
  CDL_MF_OTHER_EXP: 'Others',
  CDL_MF_TRANS_AMT: 'Transferred',
  CDL_MF_FORFEIT_AMT: 'Forfeited',
  CDL_MF_DEV_EQUITY_CONT: 'Asset Registy Equity',
  CDL_MF_AMANAT_FUND: 'Amanat Fund',
  CDL_MF_OTHER_WITHDRAW: 'Others Withdrawal',
  CDL_MF_OQOOD_OTHER_PMT: 'Ogood/Others fees and Payments',
  CDL_MF_VAT_DEPOSIT_AMT: 'Vat Deposit',
  CDL_MF_PROFIT_ERND: 'Credit Interest/ Profit earned for retention A',
  CDL_MF_REIMB_AMT: 'Re-imbursement',
  CDL_MF_PMT_FRM_RETENTION: 'Payment From Retention A/C',
  CDL_MF_CAP_VAT_AMT: 'VAT Capped',
  CDL_MF_INT_ERND_ESCROW: 'Credit Interest/ Profit earned for escrow A/C',
  CDL_MF_CLOSURE: 'Management Firm Closure',
  CDL_MF_TOTAL_AMT_RECEIVED: 'Total Income Fund',
  CDL_MF_TOTAL_DIS_PMT: 'Total Payment',
  CDL_MF_DOC_ACTION: 'Available Actions',

  // Fee details (CDL_MF_FEES_*)
  CDL_MF_FEES: 'Escrow Fee & Collection Details',
  CDL_MF_FEE_COLLECTION_DATE: 'Fee Collection Date',
  CDL_MF_CANCEL: 'Cancel',
  CDL_MF_ADDING: 'Adding...',
  CDL_MF_ADD: 'Add',
}

// Utility function to get label by configId
export const getBuildPartnerAssetLabel = (configId) => {
  return BUILD_PARTNER_ASSET_LABELS[configId] || configId
}

// Utility function to get all labels for a specific category
export const getBuildPartnerAssetLabelsByCategory = (category) => {
  const categories = {
    details: [
      'CDL_MF_DETAILS',
      'CDL_MF_REFID',
      'CDL_MF_REGNO',
      'CDL_MF_NAME',
      'CDL_MF_CLASSIFICATION',
      'CDL_MF_LOCATION',
      'CDL_MF_CIF',
      'CDL_MF_STATUS',
      'CDL_MF_ACC_STATUS',
      'CDL_MF_ACC_STATUS_DATE',
      'CDL_MF_REG_DATE',
      'CDL_MF_EST_DATE',
      'CDL_MF_EST_COMPLETION_DATE',
    ],
    retention: [
      'CDL_MF_PRIMARY_RETENTION',
      'CDL_MF_SECONDARY_RETENTION',
      'CDL_MF_AGG_RETENTION',
      'CDL_MF_RETENTION_START_DATE',
    ],
    expenses: [
      'CDL_MF_MGMT_EXPENSES',
      'CDL_MF_MARKETING_COST',
      'CDL_MF_BROK_FEES',
      'CDL_MF_ADVTG_COST',
    ],
    management: [
      'CDL_MF_SP_REG_APPROVAL',
      'CDL_MF_RES_PAYMENT_TYPE',
      'CDL_MF_ASS_MANAGER',
      'CDL_MF_BACKUP_MANAGER',
      'CDL_MF_RM',
      'CDL_MF_ARM',
      'CDL_MF_TL',
      'CDL_MF_DOC_VALIDITY',
      'CDL_MF_DOC_ACTION',
    ],
    account: [
      'CDL_MF_ACC_NO',
      'CDL_MF_ACC_IBAN',
      'CDL_MF_ACC_OPENDATE',
      'CDL_MF_ACC_NAME',
      'CDL_MF_ACC_CUR',
      'CDL_MF_ACC_RETENTION',
      'CDL_MF_ACC_SUBCONS',
      'CDL_MF_ACC_CORP',
      'CDL_MF_ACC_VALIDATION',
    ],
    beneficiary: [
      'CDL_MF_BENE_INFO',
      'CDL_MF_BENE_EXP',
      'CDL_MF_BENE_TRANSFER',
      'CDL_MF_BENE_REFID',
      'CDL_MF_BENE_NAME',
      'CDL_MF_BENE_BANK',
      'CDL_MF_BENE_ACC',
      'CDL_MF_BENE_IBAN',
      'CDL_MF_BENE_BIC',
      'CDL_MF_BENE_ROUTING',
      'CDL_MF_BENE_SWIFT',
      'CDL_MF_ACC_VAL',
      'CDL_MF_BENE_DOC_TEMPLATE',
      'CDL_MF_BENE_UPLOAD_BENE',
    ],
    payment_plan: [
      'CDL_MF_PAYMENT_PLAN',
      'CDL_MF_ADD_INSTALLMENT',
      'CDL_MF_INSTALLMENT_NO',
      'CDL_MF_INSTALLMENT_PER',
      'CDL_MF_PROJ_COM_PER',
    ],
    financial: [
      'CDL_MF_FINANCIAL',
      'CDL_MF_EST_ASS_COST',
      'CDL_MF_TOTAL_REVENUE',
      'CDL_MF_BUILD_COST',
      'CDL_MF_ASST_MGMT_EXP',
      'CDL_MF_LAND_ACQ_COST',
      'CDL_MF_MARK_EXP',
      'CDL_MF_TRAN_DATE',
      'CDL_MF_ACTUAL_ASSEST_COST',
      'CDL_MF_TOTAL_UNIT_SOLD',
      'CDL_MF_INFRA_COST',
      'CDL_MF_CASH_FROM_UNIT',
      'CDL_MF_FUND_OUT_ESCROW',
      'CDL_MF_FUND_WITHIN_ESCROW',
      'CDL_MF_TOTAL_AMOUNT',
    ],
    costs: [
      'CDL_MF_EXCEP_CAP_VAL',
      'CDL_MF_MORTGAGE_AMT',
      'CDL_MF_VAT_AMT',
      'CDL_MF_OQOOD_FEES',
      'CDL_MF_REFUND_AMT',
      'CDL_MF_TECH_FEES',
      'CDL_MF_UNALLO_COST',
      'CDL_MF_LOAN',
      'CDL_MF_OTHER_EXP',
    ],
    balances: [
      'CDL_MF_RETEN_ACC_BAL',
      'CDL_MF_TRUST_ACC_BAL',
      'CDL_MF_SUBCONS_ACC_BAL',
    ],
    transactions: [
      'CDL_MF_TRANS_AMT',
      'CDL_MF_FORFEIT_AMT',
      'CDL_MF_DEV_EQUITY_CONT',
      'CDL_MF_AMANAT_FUND',
      'CDL_MF_OTHER_WITHDRAW',
      'CDL_MF_OQOOD_OTHER_PMT',
      'CDL_MF_VAT_DEPOSIT_AMT',
      'CDL_MF_PROFIT_ERND',
      'CDL_MF_REIMB_AMT',
      'CDL_MF_PMT_FRM_RETENTION',
      'CDL_MF_CAP_VAT_AMT',
      'CDL_MF_INT_ERND_ESCROW',
    ],
    closure: [
      'CDL_MF_CLOSURE',
      'CDL_MF_TOTAL_AMT_RECEIVED',
      'CDL_MF_TOTAL_DIS_PMT',
    ],
  }

  return (
    categories[category]?.map((configId) => ({
      configId,
      label: BUILD_PARTNER_ASSET_LABELS[configId],
    })) || []
  )
}

// Export the full mapping object for direct access
export default BUILD_PARTNER_ASSET_LABELS
